app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

use catalyst\Http\VideoStream;


Route::resource('/', 'HomeController');

Route::get('siteimage/{fldname}/{filename}', function($fldname="",$filename=""){
    $path = storage_path() . '/app/public/'.$fldname.'/' . $filename;
     
    if(!File::exists($path)) { return response()->json(['message' => 'Image not found.'], 404); }
    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);
    return $response;
});


Route::get('site/{fldname}/{filename}', function($fldname="",$filename=""){
    $path = storage_path() . '/app/public/'.$fldname.'/' . $filename;
     
    if(!File::exists($path)) { return response()->json(['message' => 'video not found.'], 404); }
    $file = File::get($path);
    $type = File::mimeType($path);
    //echo $type; die;

   //echo "<pre>"; print_r($file); die;
    if($fldname=="videos"){

        $obj = new VideoStream($path,$type);
        $obj->start();
        /*echo $path;
        echo "<pre>"; print_r($obj); die;

        header('Content-Description: File Transfer');
        header("Expires: Thu, 19 Nov 1981 08:52:00 GMT");
        #header("Cache-Control: no-store, public, must-revalidate, max-age=86400");
        header("Pragma: public");
        header('Accept-Ranges: bytes');
        header('Cache-Control: max-age=604800');
        header("Content-Type: ".$type);
        //header('Content-Type: application/octet-stream');
        header("Content-Disposition: inline; filename=" .$filename);
        header("Content-Transfer-Encoding: binary");
        header("Content-Length: ".filesize($path));
        readfile($path);die();*/
    }else{
        $response = Response::make($file, 200);
        $response->header("Expires", "Thu, 19 Nov 1981 08:52:00 GMT");
        $response->header("Cache-Control", "no-store, no-cache, must-revalidate, max-age=0");
        $response->header("Pragma", "no-cache");
        $response->header("Content-Disposition", "inline; filename=".$filename);
        $response->header("Content-Length", filesize($path));
        $response->header("Content-Type", $type);
        return $response;
    }
});


Route::get('login', 'UserController@user_login');
Route::post('login',array('as'=>'user.login','uses'=>'UserController@login'));

Route::get('logout', array('uses' => 'UserController@logout'));
Route::get('register', function(){return View::make('users.user_register');});
Route::get('register', 'UserController@registerForm');
Route::post('register', array('as'=>'user.register','uses'=>'UserController@register'));
Route::get('clientinfo', function(){return View::make('users.cleint_information_form');});
Route::post('clientInfo', 'UserController@userNextForm');
Route::get('forgotpassword', function(){return View::make('users.user_forgotpassword');});
Route::post('forgotpassword', 'UserController@forgotPassword');


Route::get('contact', 'PageController@contact');
Route::get('about', 'PageController@about');

Route::post('newsletter', 'PageController@newsletter');
Route::post('contactus', 'PageController@contactUs');

Route::post('profilephoto',  array('as'=>'profilephoto','uses'=>'UserController@profilePhoto'))->middleware('auth');
Route::get('profile/{username}',  array('as'=>'profiledetail','uses'=>'UserController@profileDetail'));

//coupon
Route::post('couponcheck',  array('as'=>'couponcheck','uses'=>'CouponController@checkCoupon'));
//Login user information
Route::group(['middleware' => ['auth','normalusersauth']], function () {

    Route::get('dashboard', array('as'=>'user.dashboard','uses'=>'UserController@dashboard'));
    Route::get('profile', array('as'=>'user.profile','uses'=>'UserController@userProfile'));
    Route::post('profile', array('as'=>'user.profile','uses'=>'UserController@updateUserProfile'));
    Route::resource('video', 'VideoController');
    Route::get('video/{videoid}/process', array('as'=>'video.process','uses'=>'VideoController@process'));
    Route::post('video/{videoid}/processing', array('as'=>'video.processing','uses'=>'VideoController@processing'));
    Route::post('export', array('as'=>'video.export','uses'=>'VideoController@export'));
    Route::get('video/{videoid}/comment/{mentorid?}', array('as'=>'video.comment','uses'=>'VideoController@videoComments'));

    Route::delete('video/{videoid}/destroy', array('as'=>'video.destroy','uses'=>'VideoController@destroy'));
    Route::get('videos/reviewed', array('as'=>'video.reviewed','uses'=>'VideoController@reviewed'));
    
    Route::get('password/{id}', array('as'=>'user.password','uses'=>'UserController@updatePassword'));
    Route::post('updatepassword/{id}', array('as'=>'user.updatepassword','uses'=>'UserController@updatePasswordSave'));
    Route::get('archieve', array('as'=>'video.archieve','uses'=>'VideoController@showarchive'));

});


//Mentor router with login
Route::group(['prefix' => 'coach','middleware' => ['auth','mentorsauth']], function () {
    
    Route::get('dashboard', array('as'=>'mentor.dashboard','uses'=>'MentorController@dashboard'));
    Route::get('profile', array('as'=>'mentor.profile','uses'=>'MentorController@profile'));
    Route::post('profile',  array('as'=>'mentor.profile','uses'=>'MentorController@updateProfile'));

    Route::get('video/{videoid}/detail', array('as'=>'video.detail','uses'=>'VideoController@detail'));
    
    Route::get('video/{videoid}/comments', array('as'=>'video.comments','uses'=>'VideoController@comments'));
    Route::post('video/{videoid}/comments', array('as'=>'video.comments','uses'=>'VideoController@addComments'));
    Route::post('video/comments/{videoid}/confirm', array('as'=>'video.comments.confirm','uses'=>'VideoController@confirmComments'));
    Route::post('video/comment', array('as'=>'video.comment.delete','uses'=>'VideoController@deleteComments'));
    Route::post('video/updatecomment', array('as'=>'video.updatecomment','uses'=>'VideoController@upudateComments'));

    Route::get('videos/review', array('as'=>'videos.review','uses'=>'VideoController@review'));
    Route::get('videos/reviewed', array('as'=>'videos.reviewed','uses'=>'VideoController@reviewedMentor'));
    
    Route::get('password/{id}', array('as'=>'mentor.password','uses'=>'UserController@updatePassword'));
    Route::post('updatepassword/{id}', array('as'=>'mentor.updatepassword','uses'=>'UserController@updatePasswordSave'));
    Route::get('archieve', array('as'=>'mentor.archieve','uses'=>'VideoController@showarchiverMentor'));
});


//Admin routers

Route::group(['prefix' => 'admin','middleware' => ['auth','administrator']], function () {

    Route::get('dashboard', array('as'=>'admin.dashboard','uses'=>'AdminController@dashboard'));
    Route::get('profile', array('as'=>'admin.profile','uses'=>'AdminController@profile'));
    Route::post('profile',  array('as'=>'admin.profile','uses'=>'AdminController@updateProfile'));

    Route::get('videos', array('as'=>'admin.videos','uses'=>'VideoController@adminIndex'));
    Route::get('video/{videoid}', array('as'=>'admin.video.show','uses'=>'VideoController@adminShow'));
    Route::delete('video/{usersid}/delete', array('as'=>'admin.video.delete','uses'=>'VideoController@adminDelete'));

    //coupons Management
    Route::get('coupons', array('as'=>'admin.coupon','uses'=>'CouponController@adminIndex'));
    Route::get('coupon/{couponid}/edit', array('as'=>'admin.coupon.show','uses'=>'CouponController@adminShow'));
    Route::get('coupon/create', array('as'=>'admin.coupon.create','uses'=>'CouponController@adminCreate'));
    Route::post('coupon/{couponid}/update', array('as'=>'admin.coupon.update','uses'=>'CouponController@adminUpdate'));
    Route::post('coupon/store', array('as'=>'admin.coupon.store','uses'=>'CouponController@adminStore'));
    Route::delete('coupon/{couponid}/delete', array('as'=>'admin.coupon.delete','uses'=>'CouponController@adminDelete'));
    
    
    Route::get('users', array('as'=>'admin.users','uses'=>'UserController@adminIndex'));
    Route::get('users/create', array('as'=>'admin.users.create','uses'=>'UserController@adminCreate'));
    Route::post('users/store', array('as'=>'admin.users.store','uses'=>'UserController@adminStore'));
    Route::get('users/{usersid}/edit', array('as'=>'admin.users.edit','uses'=>'UserController@adminEdit'));
    Route::post('users/{usersid}/update', array('as'=>'admin.users.update','uses'=>'UserController@adminUpdate'));
    Route::delete('users/{usersid}/delete', array('as'=>'admin.users.delete','uses'=>'UserController@adminDelete'));


    
    Route::get('mentors', array('as'=>'admin.mentors','uses'=>'MentorController@adminIndex'));
    Route::get('mentors/{usersid}/edit', array('as'=>'admin.mentors.edit','uses'=>'MentorController@adminEdit'));
    Route::get('mentors/{usersid}/password', array('as'=>'admin.mentors.password','uses'=>'MentorController@adminPassword'));
    Route::get('mentors/create', array('as'=>'admin.mentors.create','uses'=>'MentorController@adminCreate'));
    Route::post('mentors/save', array('as'=>'admin.mentors.save','uses'=>'MentorController@adminSave'));
    Route::post('mentors/{usersid}/update', array('as'=>'admin.mentors.update','uses'=>'MentorController@adminUpdate'));
    Route::post('mentors/{usersid}/updatepassword', array('as'=>'admin.mentors.updatepassword','uses'=>'MentorController@adminUpdatePassword'));
    Route::delete('mentors/{usersid}/delete', array('as'=>'admin.mentors.delete','uses'=>'MentorController@adminDelete'));
    
    //Category Information

resources/views/includes/adminhead.blade.php
<meta charset="utf-8">
<title>@yield('title','Catalyst')</title>
<meta name="description" content="Catalyst">
<meta name="author" content="Catalyst for data">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="csrf-token" content="{{ csrf_token() }}">
<link href="https://fonts.googleapis.com/css?family=Montserrat:100,300,400,500,600,700&display=swap" rel="stylesheet"> 
<!--<link href='https://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>-->

<link href="{{ asset('css/bootstrap.min.css') }}" rel="stylesheet">
<link href="{{URL::asset('css/bootstrap-theme.min.css')}}" rel="stylesheet">
<link href="{{URL::asset('css/font-awesome.min.css')}}" rel="stylesheet">
<link href="{{URL::asset('public/vendors/owl.carousel/owl.carousel.css')}}" rel="stylesheet">
<link href="{{URL::asset('public/vendors/magnific-popup/magnific-popup.css')}}" rel="stylesheet">
<link href="{{URL::asset('public/vendors/revolution/css/settings.css')}}" rel="stylesheet">
<link href="{{URL::asset('public/vendors/revolution/css/layers.css')}}" rel="stylesheet">
<link href="{{URL::asset('public/vendors/revolution/css/navigation.css')}}" rel="stylesheet">
<link href="{{ asset('css/style.css') }}" rel="stylesheet">
<link href="{{ asset('css/theme.css') }}" rel="stylesheet">

@stack('scripts-headers') 

resources/views/includes/adminleft.blade.php
@push('scripts-footer')
<script>
    jQuery(document).ready(function(){
       jQuery("#profile_file_upload").on("change",function(){
            jQuery("#profile_img_form").ajaxSubmit({ 
                    target:   "#itftargetLayer", 
                    dataType: "json",
                    beforeSend:function(){ 
                        jQuery("#itf_progress_bar_block").removeClass("hide");
                        jQuery("#itf_progress_bar").html("0%"); 
                    },
                    beforeSubmit: function() { console.log("Before"); },
                    uploadProgress: function (event, position, total, percentComplete){                             
                        jQuery("#itf_progress_bar").css({width:percentComplete+'%'}).html(percentComplete+"%");
                    },
                    success:function (resdt){
                        jQuery("#itf_progress_bar_block").addClass("hide");    
                        if(resdt.status=="success"){
                          jQuery(".pimgchange>img").attr("src","{{asset('siteimage/users')}}/"+resdt.imagename+"?t="+new Date());
                        }
                    },
                    resetForm: false 
                });
                return false;
            });
        });
</script>
@endpush
<div class="borderwhite">
    <div class="bordergrey">
        <div class="nav-side-menu">
            <div class="text-center">
                <div class="circle130 pimgchange">
                    <?php if(!empty(Auth::user()->user_photo)): ?>
                        <img  src="{{asset('siteimage/users/'.Auth::user()->user_photo)}}" />
                    <?php else: ?>
                        <img src="{{asset('images/profile.png')}}"/>
                    <?php endif; ?>
                    <span class="profileimgchnage">
                    {!! Form::open(['route' => array('profilephoto'),'method' => 'post', 'name' => 'profile_img_form','id' => 'profile_img_form']) !!}<input name="profile_file_upload" id="profile_file_upload" class="file" type="file">{!! Form::close() !!}
                    <i class="fa fa-camera-retro fa-lg"></i></span>
                </div>
               	<div class="mt10 mb20"><?php echo Auth::user()->name; ?></div>
           </div>
            <i class="fa fa-bars  toggle-btn" data-toggle="collapse" data-target="#menu-content"></i>                          
            <div class="menu-list">
                <ul id="menu-content" class="menu-content collapse out">
                    <li><a href="{!! route('admin.dashboard') !!}">Dashboard</a></li>
                    <li ><a href="{!! route('admin.users') !!}">Users</a></li>
                    <li ><a href="{!! route('admin.mentors') !!}">Mentors</a></li>
                     <li><a href="{!! route('admin.videos') !!}">Videos</a></li>                         
                     <li><a href="{!! route('admin.category') !!}">Category </a></li>
                     <li><a href="{!! route('admin.package') !!}">Package </a></li>
                     <li><a href="{!! route('admin.coupon') !!}">Coupons </a></li>
                     <li><a href="{!! url('logout') !!}">Logout</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>	

resources/views/includes/footer.blade.php
<!--Footer-->
  	<footer class="row site-footer">
  		<div class="container">
  			<div class="row">
  				<div class="col-md-7 col-md-push-5 half-side">
  					<div class="footer-contact row footer-widget right-box">
  						<h3 class="footer-title">Contact Us</h3>
  						<ul class="nav">
  							<li class="tel"><a href="#"><i class="fa fa-phone"></i>+91 8093203113</a></li>
  							<li class="email"><a href="mailto:support@thepauseplay.com"><i class="fa fa-envelope-o"></i>support@thepauseplay.com</a></li>
  							<li><a href="#"><i class="fa fa-facebook"></i></a></li>
  							<li><a href="#"><i class="fa fa-twitter"></i></a></li>
  							<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
  							<li><a href="#"><i class="fa fa-youtube-play"></i></a></li>
  						</ul>
  					</div>
  					<div class="footer-newsletter row footer-widget right-box">
  						<h3 class="footer-title">newsletter sign up</h3>
  						<form class="form-inline newsletter-form">
							<input type="text" class="form-control" placeholder="Name">
							<input type="email" class="form-control" placeholder="Email">
							<button type="submit" class="btn btn-primary">submit</button>
						</form>
  					</div>
  				</div>
  				<div class="col-md-5 col-md-pull-7 half-side">
  					<div class="footer-about left-box footer-widget row">
  						<h3 class="footer-title">About Us</h3>
  						<p>Lorem ipsum dolor sit amet, consectetur  some dymmy adipiscing elit. Nam turpis quam, sodales in text she ante sagittis, varius efficitur mauris. Nam turpis quam, sodales in text should be able. to...</p>
  					</div>
  					<div class="copyright-row left-box footer-widget row">
                                            ©Copyright <?php echo date('Y'); ?> Pause Play. All Rights Reserved. Designed by <a target="_blank" href="https://itfosters.com/">IT Fosters</a>
  					</div>
  				</div>
  			</div>
  		</div>
  	</footer>
    
    <script src="{{URL::asset('js/jquery-2.1.4.min.js')}}"  type="text/javascript"></script>
    <script src="{{URL::asset('js/bootstrap.min.js')}}"  type="text/javascript"></script>
    <script src="{{URL::asset('vendors/magnific-popup/jquery.magnific-popup.min.js')}}"  type="text/javascript"></script>
    <script src="{{URL::asset('vendors/owlcarousel/owl.carousel.min.js')}}"  type="text/javascript"></script>
    <script src="{{URL::asset('vendors/couterup/jquery.counterup.min.js')}}"  type="text/javascript"></script>
    <script src="{{URL::asset('vendors/waypoint/waypoints.min.js')}}"  type="text/javascript"></script>
    <script src="{{URL::asset('vendors/revolution/js/jquery.themepunch.tools.min.js?rev=5.0')}}"  type="text/javascript"></script>
    <script src="{{URL::asset('vendors/revolution/js/jquery.themepunch.revolution.min.js?rev=5.0')}}"  type="text/javascript"></script>
    <script src="{{URL::asset('vendors/revolution/js/extensions/revolution.extension.video.min.js')}}"  type="text/javascript"></script>
    <script src="{{URL::asset('vendors/revolution/js/extensions/revolution.extension.slideanims.min.js')}}"  type="text/javascript"></script>
    <script src="{{URL::asset('vendors/revolution/js/extensions/revolution.extension.layeranimation.min.js')}}"  type="text/javascript"></script>
    <script src="{{URL::asset('vendors/revolution/js/extensions/revolution.extension.navigation.min.js')}}"  type="text/javascript"></script>
    <script src="{{URL::asset('js/theme.js')}}"  type="text/javascript"></script>



@stack('scripts-footer') 

resources/views/includes/head.blade.php
<meta charset="utf-8">
<title>@yield('title','Catalyst')</title>
<meta name="description" content="Catalyst">
<meta name="author" content="Catalyst for data">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="csrf-token" content="{{ csrf_token() }}">
<link href="https://fonts.googleapis.com/css?family=Montserrat:100,300,400,500,600,700&display=swap" rel="stylesheet"> 
<!--<link href='https://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>-->

<link href="{{ asset('css/bootstrap.min.css') }}" rel="stylesheet">
<link href="{{URL::asset('css/bootstrap-theme.min.css')}}" rel="stylesheet">
<link href="{{URL::asset('css/font-awesome.min.css')}}" rel="stylesheet">
<link href="{{URL::asset('public/vendors/owl.carousel/owl.carousel.css')}}" rel="stylesheet">
<link href="{{URL::asset('public/vendors/magnific-popup/magnific-popup.css')}}" rel="stylesheet">
<link href="{{URL::asset('public/vendors/revolution/css/settings.css')}}" rel="stylesheet">
<link href="{{URL::asset('public/vendors/revolution/css/layers.css')}}" rel="stylesheet">
<link href="{{URL::asset('public/vendors/revolution/css/navigation.css')}}" rel="stylesheet">
<link href="{{ asset('css/style.css') }}" rel="stylesheet">
<link href="{{ asset('css/theme.css') }}" rel="stylesheet">

@stack('scripts-headers') 

resources/views/includes/headeruser.blade.php
<a id="toggle" href="#">
	<i class="fa fa-bars"></i>
</a>
<main id="content">
	<div id="overlay"></div>
	<header>
		<div class="header">
			<div class="container from-top">
				<div class="">
					<div class="col-md-3 col-sm-3 col-xs-12">
						<div class="logo">
							<div class="logo-inner">
								<a href="{!! url('/') !!}">
									<!-- <img src="{{ asset('images/logo.png') }}"/> -->
								</a>
								<div class="clearfix"></div>
							</div>
						</div>
						<div class="clearfix"></div>
					</div>
					<div class="col-md-9 col-sm-9 col-xs-12>">

						<div class="avtar menu">
							<ul>
								<li>
									<div class="dropdown">
										<a id="dLabel" href="#itf" class="semi_bold" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
										<?php echo Auth::user()->name; ?>
											<span class="caret"></span>
											<?php if(!empty(Auth::user()->user_photo)){ ?>
												<img src="{{asset('siteimage/users/'.Auth::user()->user_photo)}}" class="circle50 hidden-xs"/>
											<?php }else{ ?>
												<img src="{{asset('images/profile.png')}}" class="circle50 hidden-xs"/>
											<?php } ?>
										</a>

										<ul class="dropdown-menu" aria-labelledby="dLabel">
											
											<?php if(Auth::user()->user_type=="M"): ?>
												<li><a href="{!! route('mentor.dashboard') !!}" >Dashboard</a></li>
												<li><a href="{!! route('mentor.profile') !!}" >Edit profile</a></li>
											<?php elseif(Auth::user()->user_type=="A"): ?>
												<li><a href="{!! route('admin.dashboard') !!}" >Dashboard</a></li>
												<li><a href="{!! route('admin.profile') !!}" >Edit profile</a></li>
											<?php else: ?>
												<li><a href="{!! route('user.dashboard') !!}" >Dashboard</a></li>
												<li><a href="{!! route('user.profile') !!}" >Edit profile</a></li>
											<?php endif; ?>
											<li><a href="{!! url('logout') !!}" >Logout</a></li>
										</ul>
									</div>
								</li>
							</ul>
	                    </div>

						<nav id="menu">
							<ul>
								<li><a href="{!! url('/') !!}" >Home</a></li>
								<li><a href="#" >About Us</a></li>
								<li><a href="#" >Contact Us</a></li>
							</ul>
						</nav>
					</div>
				</div>
			</div>
			<div class="clearfix"></div>
		</div>
	</header>

resources/views/includes/sidebar.blade.php
<!-- sidebar nav -->
    <nav id="sidebar-nav">
        <ul class="nav nav-pills nav-stacked">
            <li><a href="#">Fly to the Moon</a></li>
            <li><a href="#">Dig to China</a></li>
            <li><a href="#">Swim Across the Sea</a></li>
        </ul>
    </nav>

resources/views/includes/userleft.blade.php
@push('scripts-footer')
<script>
    jQuery(document).ready(function(){
       jQuery("#profile_file_upload").on("change",function(){
            jQuery("#profile_img_form").ajaxSubmit({ 
                    target:   "#itftargetLayer", 
                    dataType: "json",
                    beforeSend:function(){ 
                        jQuery("#itf_progress_bar_block").removeClass("hide");
                        jQuery("#itf_progress_bar").html("0%"); 
                    },
                    beforeSubmit: function() {},
                    uploadProgress: function (event, position, total, percentComplete){                             
                        jQuery("#itf_progress_bar").css({width:percentComplete+'%'}).html(percentComplete+"%");
                    },
                    success:function (resdt){
                        jQuery("#itf_progress_bar_block").addClass("hide");    
                        if(resdt.status=="success"){
                          jQuery(".pimgchange>img").attr("src","{{asset('siteimage/users')}}/"+resdt.imagename+"?t="+new Date());
                        }
                    },
                    resetForm: false 
                });
                return false;
            });
        });
</script>
@endpush
<div class="borderwhite">
    <div class="bordergrey">
        <div class="nav-side-menu">
            <div class="text-center">
                <div class="circle130 pimgchange">
                    <?php if(!empty(Auth::user()->user_photo)): ?>
                        <img src="{{asset('siteimage/users/'.Auth::user()->user_photo)}}" />
                    <?php else: ?>
                        <img src="{{asset('images/profile.png')}}"/>
                    <?php endif; ?>
                    <span class="profileimgchnage">
                    {!! Form::open(['route' => array('profilephoto'),'method' => 'post', 'name' => 'profile_img_form','id' => 'profile_img_form']) !!}<input name="profile_file_upload" id="profile_file_upload" class="file" type="file">{!! Form::close() !!}
                    <i class="fa fa-camera-retro fa-lg"></i></span>
                </div>
               	<div class="mt10 mb20"><?php echo Auth::user()->name; ?></div>
           </div>
            <i class="fa fa-bars  toggle-btn" data-toggle="collapse" data-target="#menu-content"></i>                          
            <div class="menu-list">
                <ul id="menu-content" class="menu-content collapse out">
                    <li><a href="{!! url('dashboard') !!}">Dashboard</a></li>
                    <!-- <li ><a href="{!! route('video.create') !!}">Upload Video</a></li> -->
<!--                     <li><a href="{{ route('video.index') }}">Uploaded Videos</a></li>                         
                     <li><a href="{{ route('video.reviewed') }}">Reflection Videos</a></li>-->
                     <!-- <li><a href="{!! route('video.archieve') !!}" title="Archived Videos">Archived Videos </a></li> -->
                     <li><a href="{!! url('logout') !!}">Logout</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>	